/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author BIMA
 */
public class FormResep extends javax.swing.JFrame {

    // fields (deklarasi di class level)
    private controller.RecipeController controller = new controller.RecipeController();
    private javax.swing.table.DefaultTableModel tableModel;
    private String selectedImagePath = null; // path gambar dipilih
    
    public FormResep() {
        initComponents();
        
        // init kategori
        cmbKategori.removeAllItems();
        cmbKategori.addItem("Makanan");
        cmbKategori.addItem("Minuman");
        cmbKategori.addItem("Dessert");
        cmbKategori.addItem("Lainnya");

        // init table
        tableModel = new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Judul", "Kategori", "Favorite"}, 0) {
            @Override public boolean isCellEditable(int row, int col) { return false; }
        };
        tblResep.setModel(tableModel);
        
        // disable tombol yang belum boleh
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);

        loadTableData();
        
        KeyAdapter ka = new KeyAdapter() {
            public void keyReleased(KeyEvent e) {
                boolean ok = !txtJudul.getText().trim().isEmpty()
                          && !txtIngredients.getText().trim().isEmpty()
                          && !txtInstructions.getText().trim().isEmpty();
                btnTambah.setEnabled(ok);
            }
        };
        txtJudul.addKeyListener(ka);
        txtIngredients.addKeyListener(ka);
        txtInstructions.addKeyListener(ka);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngredients = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstructions = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        txtJudul = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblImagePreview = new javax.swing.JLabel();
        btnChooseImage = new javax.swing.JButton();
        chkFavorite = new javax.swing.JCheckBox();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResep = new javax.swing.JTable();
        btnImportTXT = new javax.swing.JButton();
        btnExportTXT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("🍽️  APLIKASI RESEP MAKANAN  🍴");
        jPanel1.add(jLabel1);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Judul Resep :");

        jLabel3.setText("Kategori :");

        txtIngredients.setColumns(20);
        txtIngredients.setRows(5);
        jScrollPane1.setViewportView(txtIngredients);

        txtInstructions.setColumns(20);
        txtInstructions.setRows(5);
        jScrollPane2.setViewportView(txtInstructions);

        jLabel4.setText("Bahan-bahan :");

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Cara Membuat :");

        jLabel6.setText("Gambar Resep :");

        lblImagePreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChooseImage.setText("Pilih Gambar");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        chkFavorite.setText("Favorit resep ini");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnChooseImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkFavorite))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(chkFavorite))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChooseImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Cari Resep :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        jPanel3.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 177;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanel3.add(txtSearch, gridBagConstraints);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 12);
        jPanel3.add(btnSearch, gridBagConstraints);

        tblResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResepMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblResep);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 387;
        gridBagConstraints.ipady = 601;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 12);
        jPanel3.add(jScrollPane3, gridBagConstraints);

        btnImportTXT.setText("Import");
        btnImportTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportTXTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 42, 12, 0);
        jPanel3.add(btnImportTXT, gridBagConstraints);

        btnExportTXT.setText("Export");
        btnExportTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportTXTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 12, 12);
        jPanel3.add(btnExportTXT, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        int r = chooser.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            selectedImagePath = f.getAbsolutePath();
            // preview scaled
            ImageIcon icon = new ImageIcon(new ImageIcon(selectedImagePath).getImage().getScaledInstance(
                    lblImagePreview.getWidth(), lblImagePreview.getHeight(), java.awt.Image.SCALE_SMOOTH));
            lblImagePreview.setIcon(icon);
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String judul = txtJudul.getText().trim();
        String category = (String)cmbKategori.getSelectedItem();
        String ingredients = txtIngredients.getText().trim();
        String instructions = txtInstructions.getText().trim();
        boolean fav = chkFavorite.isSelected();

        if (judul.isEmpty() || ingredients.isEmpty() || instructions.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul, bahan, dan langkah wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            model.Recipe r = new model.Recipe(0, judul, ingredients, instructions, category, selectedImagePath, fav);
            controller.add(r);
            loadTableData();
            JOptionPane.showMessageDialog(this, "Resep berhasil ditambahkan!");
            // reset fields
            txtJudul.setText(""); txtIngredients.setText(""); txtInstructions.setText(""); chkFavorite.setSelected(false);
            lblImagePreview.setIcon(null); selectedImagePath = null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menambah resep: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblResepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResepMouseClicked
        int row = tblResep.getSelectedRow();
        if (row >= 0) {
            int id = (int) tableModel.getValueAt(row, 0);
            try {
                // ambil detail dari DAO (atau gunakan controller.getAll lalu cari id)
                java.util.List<model.Recipe> list = controller.getAll();
                model.Recipe sel = null;
                for (model.Recipe rr : list) if (rr.getId() == id) { sel = rr; break; }
                if (sel != null) {
                    txtJudul.setText(sel.getTitle());
                    txtIngredients.setText(sel.getIngredients());
                    txtInstructions.setText(sel.getInstructions());
                    cmbKategori.setSelectedItem(sel.getCategory());
                    chkFavorite.setSelected(sel.isFavorite());
                    selectedImagePath = sel.getImagePath();
                    if (selectedImagePath != null) {
                        ImageIcon icon = new ImageIcon(new ImageIcon(selectedImagePath).getImage().getScaledInstance(
                            lblImagePreview.getWidth(), lblImagePreview.getHeight(), java.awt.Image.SCALE_SMOOTH));
                        lblImagePreview.setIcon(icon);
                    } else lblImagePreview.setIcon(null);

                    // aktifkan tombol ubah/hapus
                    btnUbah.setEnabled(true); btnHapus.setEnabled(true);
                }
            } catch (Exception e) { e.printStackTrace(); }
        }
    }//GEN-LAST:event_tblResepMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int row = tblResep.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pilih resep dulu!"); return; }
        int id = (int) tableModel.getValueAt(row, 0);
        String judul = txtJudul.getText().trim();
        String category = (String)cmbKategori.getSelectedItem();
        String ingredients = txtIngredients.getText().trim();
        String instructions = txtInstructions.getText().trim();
        boolean fav = chkFavorite.isSelected();

        if (judul.isEmpty() || ingredients.isEmpty() || instructions.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Judul, bahan, dan langkah wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            model.Recipe r = new model.Recipe(id, judul, ingredients, instructions, category, selectedImagePath, fav);
            controller.update(r);
            loadTableData();
            JOptionPane.showMessageDialog(this, "Resep berhasil diubah!");
            // reset & disable
            txtJudul.setText(""); txtIngredients.setText(""); txtInstructions.setText("");
            chkFavorite.setSelected(false); lblImagePreview.setIcon(null); selectedImagePath = null;
            btnUbah.setEnabled(false); btnHapus.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblResep.getSelectedRow();
        if (row < 0) { JOptionPane.showMessageDialog(this, "Pilih resep dulu!"); return; }
        int id = (int) tableModel.getValueAt(row, 0);
        int ans = JOptionPane.showConfirmDialog(this, "Hapus resep terpilih?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {
            try {
                controller.delete(id);
                loadTableData();
                JOptionPane.showMessageDialog(this, "Resep dihapus.");
                // reset input
                txtJudul.setText(""); txtIngredients.setText(""); txtInstructions.setText("");
                lblImagePreview.setIcon(null); selectedImagePath = null;
                btnUbah.setEnabled(false); btnHapus.setEnabled(false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtJudul.setText(""); txtIngredients.setText(""); txtInstructions.setText("");
        cmbKategori.setSelectedIndex(0); chkFavorite.setSelected(false);
        lblImagePreview.setIcon(null); selectedImagePath = null;
        tblResep.clearSelection();
        btnUbah.setEnabled(false); btnHapus.setEnabled(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String kw = txtSearch.getText().trim();
        try {
            java.util.List<model.Recipe> found = controller.search(kw);
            tableModel.setRowCount(0);
            for (model.Recipe r : found) tableModel.addRow(new Object[]{r.getId(), r.getTitle(), r.getCategory(), r.isFavorite()});
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal cari: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnExportTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportTXTActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new File("resep.txt"));

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();

            try (BufferedWriter bw = new BufferedWriter(new FileWriter(f))) {

                for (model.Recipe r : controller.getAll()) {

                    bw.write("ID       : " + r.getId() + "\n");
                    bw.write("Judul    : " + r.getTitle() + "\n");
                    bw.write("Kategori : " + r.getCategory() + "\n");
                    bw.write("Favorite : " + (r.isFavorite() ? "Ya" : "Tidak") + "\n");
                    bw.write("Bahan    :\n" + r.getIngredients() + "\n");
                    bw.write("Langkah  :\n" + r.getInstructions() + "\n");
                    bw.write("Gambar   : " + (r.getImagePath()==null?"Tidak ada":r.getImagePath()) + "\n");
                    bw.write("----------------------------------------\n\n");
                }

                JOptionPane.showMessageDialog(this, "Export Pretty TXT selesai!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal export: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExportTXTActionPerformed

    private void btnImportTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportTXTActionPerformed
        JFileChooser chooser = new JFileChooser();

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();

            try (BufferedReader br = new BufferedReader(new FileReader(f))) {

                String line;
                String title = "", category = "", img = null;
                StringBuilder ing = new StringBuilder();
                StringBuilder instr = new StringBuilder();
                boolean fav = false;

                boolean readIngredients = false;
                boolean readInstructions = false;

                while ((line = br.readLine()) != null) {

                    // reset jika sampai separator
                    if (line.startsWith("--------------------------------")) {

                        // simpan 1 resep lengkap
                        if (!title.isEmpty()) {
                            model.Recipe r = new model.Recipe(
                                0,
                                title,
                                ing.toString().trim(),
                                instr.toString().trim(),
                                category,
                                img,
                                fav
                            );
                            controller.add(r);
                        }

                        // reset semua
                        title = ""; category = ""; img = null;
                        ing.setLength(0); instr.setLength(0);
                        fav = false;
                        readIngredients = false;
                        readInstructions = false;

                        continue;
                    }

                    if (line.startsWith("Judul")) {
                        title = line.substring(line.indexOf(":") + 1).trim();
                        continue;
                    }

                    if (line.startsWith("Kategori")) {
                        category = line.substring(line.indexOf(":") + 1).trim();
                        continue;
                    }

                    if (line.startsWith("Favorite")) {
                        fav = line.contains("Ya");
                        continue;
                    }

                    if (line.startsWith("Bahan")) {
                        readIngredients = true;
                        readInstructions = false;
                        continue;
                    }

                    if (line.startsWith("Langkah")) {
                        readInstructions = true;
                        readIngredients = false;
                        continue;
                    }

                    if (line.startsWith("Gambar")) {
                        img = line.substring(line.indexOf(":") + 1).trim();
                        if (img.equalsIgnoreCase("Tidak ada")) img = null;
                        readIngredients = false;
                        readInstructions = false;
                        continue;
                    }

                    // MULTILINE HANDLER
                    if (readIngredients) {
                        ing.append(line).append("\n");
                    } else if (readInstructions) {
                        instr.append(line).append("\n");
                    }
                }

                loadTableData();
                JOptionPane.showMessageDialog(this, "Import TXT Selesai!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal import: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnImportTXTActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilihan = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin keluar dari aplikasi?",
            "Konfirmasi Keluar",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (pilihan == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormResep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnExportTXT;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImportTXT;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox chkFavorite;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JTable tblResep;
    private javax.swing.JTextArea txtIngredients;
    private javax.swing.JTextArea txtInstructions;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        try {
            tableModel.setRowCount(0);
            for (model.Recipe r : controller.getAll()) {
                tableModel.addRow(new Object[]{r.getId(), r.getTitle(), r.getCategory(), r.isFavorite()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

    private String[] splitCsvLine(String line) {
        List<String> out = new ArrayList<>();
        StringBuilder cur = new StringBuilder();
        boolean inQuotes = false;
        for (int i=0;i<line.length();i++) {
            char c = line.charAt(i);
            if (c=='"' ) { inQuotes = !inQuotes; }
            else if (c==',' && !inQuotes) { out.add(cur.toString()); cur.setLength(0); }
            else cur.append(c);
        }
        out.add(cur.toString());
        return out.toArray(new String[0]);
    }
    private String unquote(String s) { if (s==null) return ""; if (s.startsWith("\"") && s.endsWith("\"")) return s.substring(1,s.length()-1).replace("\"\"","\""); return s; }

}
